package com.dingjinllin.study.yanfang.xiyanfang;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.VerticalLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p/>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p/>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Xyyf_xinxi extends VerticalLayout {
    protected TextField bt_lb1;
    protected Button bt_dyflb;
    protected TextArea ta_yfgx;
    protected Button bt_bjyfgx;
    protected TextField bt_lb2;
    protected TextField bt_lb3;
    protected TextArea ta_yfsm;
    protected Button bf_bjyfsm;
    protected TextField bt_lb4;
    protected TextField tf_fm;
    protected TextField tf_pym;
    protected TextField bt_wbm;

    public Xyyf_xinxi() {
        Design.read(this);
    }
}
